# This is a basic workflow to help you get started with Actions

name: CI2

on:
  workflow_dispatch:
env:
  cat_name: "Puszek"
  WORKFLOW_VAR: "Workflow Scope Variable"

jobs:
  display-variables:
    name: ${{ vars.cat_name }}
    runs-on: ubuntu-latest
    steps:
    - name: Use variables 1
      run: |
        echo "Repository variable : ${{ vars.REPOSITORY_VAR }}"
        echo "Organization variable : ${{ vars.ORGANIZATION_VAR }}"
        echo "Environment variable : ${{ vars.ENVIRONMENT_VAR }}"
        echo "Alice has a cat named ${{ env.cat_name }}"
        echo "Should be variable in workflow scope:$WORKFLOW_VAR"
        echo "Should be variable in job scope:$JOB_VAR"
        echo "Should be variable in step scope:$STEP_VAR"
    
    - name: Use variables 2
      run: |
        echo "Alice has a cat named <PRINT HERE THE CAT NAME STORED IN THE cat_name VARIABLE>"
        echo "Should be variable in workflow scope:$WORKFLOW_VAR"
        echo "Should be variable in job scope:$JOB_VAR"
        echo "Should NOT be variable in step scope:$STEP_VAR"

  display-variables2:
    runs-on: ubuntu-latest
    steps:
    - name: Use variables in display-variables2
      run: |
        echo "Should be variable in workflow scope:$WORKFLOW_VAR"
        echo "Should NOT be variable in job scope:$JOB_VAR"
        echo "Should NOT be variable in step scope:$STEP_VAR"
