# This is a basic workflow to help you get started with Actions

name: CI2

on:
  workflow_dispatch:
env:
  cat_name: "Puszek"
  WORKFLOW_VAR: "Workflow Scope Variable"

jobs:
  display-variables:
    environment: test
    name: ${{ vars.cat_name }}
    env:
      JOB_VAR: "Job Scope Variable"
    runs-on: ubuntu-latest
    steps:
    - name: Use variables 1
      env:
        STEP_VAR: "Step Scope Variable 1"
      run: |
        echo "Repository variable : ${{ env.REPOSITORY_VAR }}"
        echo "Organization variable : ${{ env.ORGANIZATION_VAR }}"
        echo "Environment variable : ${{ env.ENVIRONMENT_VAR }}"
        echo "Alice has a cat named ${{ env.cat_name }}"
        echo "Should be variable in workflow ${{ env.WORKFLOW_VAR }}"
        echo "Should be variable in job ${{ env.JOB_VAR }}"
        echo "Should be variable in step ${{ env.STEP_VAR }}"
    
    - name: Use variables 2
      run: |
        echo "Alice has a cat named ${{ env.cat_name }}"
        echo "Should be variable in workflow ${{ env.WORKFLOW_VAR }}"
        echo "Should be variable in job ${{ env.JOB_VAR }}"
        echo "Should NOT be variable in step ${{ env.STEP_VAR }}"

  display-variables2:
    runs-on: ubuntu-latest
    steps:
    - name: Use variables in display-variables2
      run: |
        echo "Should be variable in workflow ${{ env.WORKFLOW_VAR }}"
        echo "Should NOT be variable in job ${{ env.JOB_VAR }}"
        echo "Should NOT be variable in step ${{ env.STEP_VAR }}"
